// Helper function to get flag URL
const getFlagUrl = (code) =>
  `https://flagcdn.com/w40/${code.toLowerCase()}.png`;

export const countries = [
  { code: "AD", name: "Andorra", flag: getFlagUrl("AD") },
  { code: "AE", name: "United Arab Emirates", flag: getFlagUrl("AE") },
  { code: "AE", name: "UAE", flag: getFlagUrl("AE") },
  { code: "AF", name: "Afghanistan", flag: getFlagUrl("AF") },
  { code: "AG", name: "Antigua and Barbuda", flag: getFlagUrl("AG") },
  { code: "AI", name: "Anguilla", flag: getFlagUrl("AI") },
  { code: "AL", name: "Albania", flag: getFlagUrl("AL") },
  { code: "AM", name: "Armenia", flag: getFlagUrl("AM") },
  { code: "AO", name: "Angola", flag: getFlagUrl("AO") },
  { code: "AQ", name: "Antarctica", flag: getFlagUrl("AQ") },
  { code: "AR", name: "Argentina", flag: getFlagUrl("AR") },
  { code: "AS", name: "American Samoa", flag: getFlagUrl("AS") },
  { code: "AT", name: "Austria", flag: getFlagUrl("AT") },
  { code: "AU", name: "Australia", flag: getFlagUrl("AU") },
  { code: "AW", name: "Aruba", flag: getFlagUrl("AW") },
  { code: "AX", name: "Åland Islands", flag: getFlagUrl("AX") },
  { code: "AZ", name: "Azerbaijan", flag: getFlagUrl("AZ") },
  { code: "BA", name: "Bosnia and Herzegovina", flag: getFlagUrl("BA") },
  { code: "BB", name: "Barbados", flag: getFlagUrl("BB") },
  { code: "BD", name: "Bangladesh", flag: getFlagUrl("BD") },
  { code: "BE", name: "Belgium", flag: getFlagUrl("BE") },
  { code: "BF", name: "Burkina Faso", flag: getFlagUrl("BF") },
  { code: "BG", name: "Bulgaria", flag: getFlagUrl("BG") },
  { code: "BH", name: "Bahrain", flag: getFlagUrl("BH") },
  { code: "BI", name: "Burundi", flag: getFlagUrl("BI") },
  { code: "BJ", name: "Benin", flag: getFlagUrl("BJ") },
  { code: "BL", name: "Saint Barthélemy", flag: getFlagUrl("BL") },
  { code: "BM", name: "Bermuda", flag: getFlagUrl("BM") },
  { code: "BN", name: "Brunei", flag: getFlagUrl("BN") },
  { code: "BO", name: "Bolivia", flag: getFlagUrl("BO") },
  { code: "BQ", name: "Caribbean Netherlands", flag: getFlagUrl("BQ") },
  { code: "BR", name: "Brazil", flag: getFlagUrl("BR") },
  { code: "BS", name: "Bahamas", flag: getFlagUrl("BS") },
  { code: "BT", name: "Bhutan", flag: getFlagUrl("BT") },
  { code: "BV", name: "Bouvet Island", flag: getFlagUrl("BV") },
  { code: "BW", name: "Botswana", flag: getFlagUrl("BW") },
  { code: "BY", name: "Belarus", flag: getFlagUrl("BY") },
  { code: "BZ", name: "Belize", flag: getFlagUrl("BZ") },
  { code: "CA", name: "Canada", flag: getFlagUrl("CA") },
  { code: "CC", name: "Cocos Islands", flag: getFlagUrl("CC") },
  {
    code: "CD",
    name: "Democratic Republic of the Congo",
    flag: getFlagUrl("CD"),
  },
  { code: "CF", name: "Central African Republic", flag: getFlagUrl("CF") },
  { code: "CG", name: "Republic of the Congo", flag: getFlagUrl("CG") },
  { code: "CH", name: "Switzerland", flag: getFlagUrl("CH") },
  { code: "CI", name: "Côte d'Ivoire", flag: getFlagUrl("CI") },
  { code: "CK", name: "Cook Islands", flag: getFlagUrl("CK") },
  { code: "CL", name: "Chile", flag: getFlagUrl("CL") },
  { code: "CM", name: "Cameroon", flag: getFlagUrl("CM") },
  { code: "CN", name: "China", flag: getFlagUrl("CN") },
  { code: "CO", name: "Colombia", flag: getFlagUrl("CO") },
  { code: "CR", name: "Costa Rica", flag: getFlagUrl("CR") },
  { code: "CU", name: "Cuba", flag: getFlagUrl("CU") },
  { code: "CV", name: "Cape Verde", flag: getFlagUrl("CV") },
  { code: "CW", name: "Curaçao", flag: getFlagUrl("CW") },
  { code: "CX", name: "Christmas Island", flag: getFlagUrl("CX") },
  { code: "CY", name: "Cyprus", flag: getFlagUrl("CY") },
  { code: "CZ", name: "Czech Republic", flag: getFlagUrl("CZ") },
  { code: "DE", name: "Germany", flag: getFlagUrl("DE") },
  { code: "DJ", name: "Djibouti", flag: getFlagUrl("DJ") },
  { code: "DK", name: "Denmark", flag: getFlagUrl("DK") },
  { code: "DM", name: "Dominica", flag: getFlagUrl("DM") },
  { code: "DO", name: "Dominican Republic", flag: getFlagUrl("DO") },
  { code: "DZ", name: "Algeria", flag: getFlagUrl("DZ") },
  { code: "EC", name: "Ecuador", flag: getFlagUrl("EC") },
  { code: "EE", name: "Estonia", flag: getFlagUrl("EE") },
  { code: "EG", name: "Egypt", flag: getFlagUrl("EG") },
  { code: "EH", name: "Western Sahara", flag: getFlagUrl("EH") },
  { code: "ER", name: "Eritrea", flag: getFlagUrl("ER") },
  { code: "ES", name: "Spain", flag: getFlagUrl("ES") },
  { code: "ET", name: "Ethiopia", flag: getFlagUrl("ET") },
  { code: "FI", name: "Finland", flag: getFlagUrl("FI") },
  { code: "FJ", name: "Fiji", flag: getFlagUrl("FJ") },
  { code: "FK", name: "Falkland Islands", flag: getFlagUrl("FK") },
  { code: "FM", name: "Micronesia", flag: getFlagUrl("FM") },
  { code: "FO", name: "Faroe Islands", flag: getFlagUrl("FO") },
  { code: "FR", name: "France", flag: getFlagUrl("FR") },
  { code: "GA", name: "Gabon", flag: getFlagUrl("GA") },
  { code: "GB", name: "United Kingdom", flag: getFlagUrl("GB") },
  { code: "GB", name: "UK", flag: getFlagUrl("GB") },
  { code: "GD", name: "Grenada", flag: getFlagUrl("GD") },
  { code: "GE", name: "Georgia", flag: getFlagUrl("GE") },
  { code: "GF", name: "French Guiana", flag: getFlagUrl("GF") },
  { code: "GG", name: "Guernsey", flag: getFlagUrl("GG") },
  { code: "GH", name: "Ghana", flag: getFlagUrl("GH") },
  { code: "GI", name: "Gibraltar", flag: getFlagUrl("GI") },
  { code: "GL", name: "Greenland", flag: getFlagUrl("GL") },
  { code: "GM", name: "Gambia", flag: getFlagUrl("GM") },
  { code: "GN", name: "Guinea", flag: getFlagUrl("GN") },
  { code: "GP", name: "Guadeloupe", flag: getFlagUrl("GP") },
  { code: "GQ", name: "Equatorial Guinea", flag: getFlagUrl("GQ") },
  { code: "GR", name: "Greece", flag: getFlagUrl("GR") },
  {
    code: "GS",
    name: "South Georgia and the South Sandwich Islands",
    flag: getFlagUrl("GS"),
  },
  { code: "GT", name: "Guatemala", flag: getFlagUrl("GT") },
  { code: "GU", name: "Guam", flag: getFlagUrl("GU") },
  { code: "GW", name: "Guinea-Bissau", flag: getFlagUrl("GW") },
  { code: "GY", name: "Guyana", flag: getFlagUrl("GY") },
  { code: "HK", name: "Hong Kong", flag: getFlagUrl("HK") },
  {
    code: "HM",
    name: "Heard Island and McDonald Islands",
    flag: getFlagUrl("HM"),
  },
  { code: "HN", name: "Honduras", flag: getFlagUrl("HN") },
  { code: "HR", name: "Croatia", flag: getFlagUrl("HR") },
  { code: "HT", name: "Haiti", flag: getFlagUrl("HT") },
  { code: "HU", name: "Hungary", flag: getFlagUrl("HU") },
  { code: "ID", name: "Indonesia", flag: getFlagUrl("ID") },
  { code: "IE", name: "Ireland", flag: getFlagUrl("IE") },
  { code: "IL", name: "Israel", flag: getFlagUrl("IL") },
  { code: "IM", name: "Isle of Man", flag: getFlagUrl("IM") },
  { code: "IN", name: "India", flag: getFlagUrl("IN") },
  {
    code: "IO",
    name: "British Indian Ocean Territory",
    flag: getFlagUrl("IO"),
  },
  { code: "IQ", name: "Iraq", flag: getFlagUrl("IQ") },
  { code: "IR", name: "Iran", flag: getFlagUrl("IR") },
  { code: "IS", name: "Iceland", flag: getFlagUrl("IS") },
  { code: "IT", name: "Italy", flag: getFlagUrl("IT") },
  { code: "JE", name: "Jersey", flag: getFlagUrl("JE") },
  { code: "JM", name: "Jamaica", flag: getFlagUrl("JM") },
  { code: "JO", name: "Jordan", flag: getFlagUrl("JO") },
  { code: "JP", name: "Japan", flag: getFlagUrl("JP") },
  { code: "KE", name: "Kenya", flag: getFlagUrl("KE") },
  { code: "KG", name: "Kyrgyzstan", flag: getFlagUrl("KG") },
  { code: "KH", name: "Cambodia", flag: getFlagUrl("KH") },
  { code: "KI", name: "Kiribati", flag: getFlagUrl("KI") },
  { code: "KM", name: "Comoros", flag: getFlagUrl("KM") },
  { code: "KN", name: "Saint Kitts and Nevis", flag: getFlagUrl("KN") },
  { code: "KP", name: "North Korea", flag: getFlagUrl("KP") },
  { code: "KR", name: "South Korea", flag: getFlagUrl("KR") },
  { code: "KW", name: "Kuwait", flag: getFlagUrl("KW") },
  { code: "KY", name: "Cayman Islands", flag: getFlagUrl("KY") },
  { code: "KZ", name: "Kazakhstan", flag: getFlagUrl("KZ") },
  { code: "LA", name: "Laos", flag: getFlagUrl("LA") },
  { code: "LB", name: "Lebanon", flag: getFlagUrl("LB") },
  { code: "LC", name: "Saint Lucia", flag: getFlagUrl("LC") },
  { code: "LI", name: "Liechtenstein", flag: getFlagUrl("LI") },
  { code: "LK", name: "Sri Lanka", flag: getFlagUrl("LK") },
  { code: "LR", name: "Liberia", flag: getFlagUrl("LR") },
  { code: "LS", name: "Lesotho", flag: getFlagUrl("LS") },
  { code: "LT", name: "Lithuania", flag: getFlagUrl("LT") },
  { code: "LU", name: "Luxembourg", flag: getFlagUrl("LU") },
  { code: "LV", name: "Latvia", flag: getFlagUrl("LV") },
  { code: "LY", name: "Libya", flag: getFlagUrl("LY") },
  { code: "MA", name: "Morocco", flag: getFlagUrl("MA") },
  { code: "MC", name: "Monaco", flag: getFlagUrl("MC") },
  { code: "MD", name: "Moldova", flag: getFlagUrl("MD") },
  { code: "ME", name: "Montenegro", flag: getFlagUrl("ME") },
  { code: "MF", name: "Saint Martin", flag: getFlagUrl("MF") },
  { code: "MG", name: "Madagascar", flag: getFlagUrl("MG") },
  { code: "MH", name: "Marshall Islands", flag: getFlagUrl("MH") },
  { code: "MK", name: "North Macedonia", flag: getFlagUrl("MK") },
  { code: "ML", name: "Mali", flag: getFlagUrl("ML") },
  { code: "MM", name: "Myanmar", flag: getFlagUrl("MM") },
  { code: "MN", name: "Mongolia", flag: getFlagUrl("MN") },
  { code: "MO", name: "Macao", flag: getFlagUrl("MO") },
  { code: "MP", name: "Northern Mariana Islands", flag: getFlagUrl("MP") },
  { code: "MQ", name: "Martinique", flag: getFlagUrl("MQ") },
  { code: "MR", name: "Mauritania", flag: getFlagUrl("MR") },
  { code: "MS", name: "Montserrat", flag: getFlagUrl("MS") },
  { code: "MT", name: "Malta", flag: getFlagUrl("MT") },
  { code: "MU", name: "Mauritius", flag: getFlagUrl("MU") },
  { code: "MV", name: "Maldives", flag: getFlagUrl("MV") },
  { code: "MW", name: "Malawi", flag: getFlagUrl("MW") },
  { code: "MX", name: "Mexico", flag: getFlagUrl("MX") },
  { code: "MY", name: "Malaysia", flag: getFlagUrl("MY") },
  { code: "MZ", name: "Mozambique", flag: getFlagUrl("MZ") },
  { code: "NA", name: "Namibia", flag: getFlagUrl("NA") },
  { code: "NC", name: "New Caledonia", flag: getFlagUrl("NC") },
  { code: "NE", name: "Niger", flag: getFlagUrl("NE") },
  { code: "NF", name: "Norfolk Island", flag: getFlagUrl("NF") },
  { code: "NG", name: "Nigeria", flag: getFlagUrl("NG") },
  { code: "NI", name: "Nicaragua", flag: getFlagUrl("NI") },
  { code: "NL", name: "Netherlands", flag: getFlagUrl("NL") },
  { code: "NO", name: "Norway", flag: getFlagUrl("NO") },
  { code: "NP", name: "Nepal", flag: getFlagUrl("NP") },
  { code: "NR", name: "Nauru", flag: getFlagUrl("NR") },
  { code: "NU", name: "Niue", flag: getFlagUrl("NU") },
  { code: "NZ", name: "New Zealand", flag: getFlagUrl("NZ") },
  { code: "OM", name: "Oman", flag: getFlagUrl("OM") },
  { code: "PA", name: "Panama", flag: getFlagUrl("PA") },
  { code: "PE", name: "Peru", flag: getFlagUrl("PE") },
  { code: "PF", name: "French Polynesia", flag: getFlagUrl("PF") },
  { code: "PG", name: "Papua New Guinea", flag: getFlagUrl("PG") },
  { code: "PH", name: "Philippines", flag: getFlagUrl("PH") },
  { code: "PK", name: "Pakistan", flag: getFlagUrl("PK") },
  { code: "PL", name: "Poland", flag: getFlagUrl("PL") },
  { code: "PM", name: "Saint Pierre and Miquelon", flag: getFlagUrl("PM") },
  { code: "PN", name: "Pitcairn Islands", flag: getFlagUrl("PN") },
  { code: "PR", name: "Puerto Rico", flag: getFlagUrl("PR") },
  { code: "PS", name: "Palestine", flag: getFlagUrl("PS") },
  { code: "PT", name: "Portugal", flag: getFlagUrl("PT") },
  { code: "PW", name: "Palau", flag: getFlagUrl("PW") },
  { code: "PY", name: "Paraguay", flag: getFlagUrl("PY") },
  { code: "QA", name: "Qatar", flag: getFlagUrl("QA") },
  { code: "RE", name: "Réunion", flag: getFlagUrl("RE") },
  { code: "RO", name: "Romania", flag: getFlagUrl("RO") },
  { code: "RS", name: "Serbia", flag: getFlagUrl("RS") },
  { code: "RU", name: "Russia", flag: getFlagUrl("RU") },
  { code: "RW", name: "Rwanda", flag: getFlagUrl("RW") },
  { code: "SA", name: "Saudi Arabia", flag: getFlagUrl("SA") },
  { code: "SB", name: "Solomon Islands", flag: getFlagUrl("SB") },
  { code: "SC", name: "Seychelles", flag: getFlagUrl("SC") },
  { code: "SD", name: "Sudan", flag: getFlagUrl("SD") },
  { code: "SE", name: "Sweden", flag: getFlagUrl("SE") },
  { code: "SG", name: "Singapore", flag: getFlagUrl("SG") },
  { code: "SH", name: "Saint Helena", flag: getFlagUrl("SH") },
  { code: "SI", name: "Slovenia", flag: getFlagUrl("SI") },
  { code: "SJ", name: "Svalbard and Jan Mayen", flag: getFlagUrl("SJ") },
  { code: "SK", name: "Slovakia", flag: getFlagUrl("SK") },
  { code: "SL", name: "Sierra Leone", flag: getFlagUrl("SL") },
  { code: "SM", name: "San Marino", flag: getFlagUrl("SM") },
  { code: "SN", name: "Senegal", flag: getFlagUrl("SN") },
  { code: "SO", name: "Somalia", flag: getFlagUrl("SO") },
  { code: "SR", name: "Suriname", flag: getFlagUrl("SR") },
  { code: "SS", name: "South Sudan", flag: getFlagUrl("SS") },
  { code: "ST", name: "São Tomé and Príncipe", flag: getFlagUrl("ST") },
  { code: "SV", name: "El Salvador", flag: getFlagUrl("SV") },
  { code: "SX", name: "Sint Maarten", flag: getFlagUrl("SX") },
  { code: "SY", name: "Syria", flag: getFlagUrl("SY") },
  { code: "SZ", name: "Eswatini", flag: getFlagUrl("SZ") },
  { code: "TC", name: "Turks and Caicos Islands", flag: getFlagUrl("TC") },
  { code: "TD", name: "Chad", flag: getFlagUrl("TD") },
  { code: "TF", name: "French Southern Territories", flag: getFlagUrl("TF") },
  { code: "TG", name: "Togo", flag: getFlagUrl("TG") },
  { code: "TH", name: "Thailand", flag: getFlagUrl("TH") },
  { code: "TJ", name: "Tajikistan", flag: getFlagUrl("TJ") },
  { code: "TK", name: "Tokelau", flag: getFlagUrl("TK") },
  { code: "TL", name: "Timor-Leste", flag: getFlagUrl("TL") },
  { code: "TM", name: "Turkmenistan", flag: getFlagUrl("TM") },
  { code: "TN", name: "Tunisia", flag: getFlagUrl("TN") },
  { code: "TO", name: "Tonga", flag: getFlagUrl("TO") },
  { code: "TR", name: "Turkey", flag: getFlagUrl("TR") },
  { code: "TT", name: "Trinidad and Tobago", flag: getFlagUrl("TT") },
  { code: "TV", name: "Tuvalu", flag: getFlagUrl("TV") },
  { code: "TW", name: "Taiwan", flag: getFlagUrl("TW") },
  { code: "TZ", name: "Tanzania", flag: getFlagUrl("TZ") },
  { code: "UA", name: "Ukraine", flag: getFlagUrl("UA") },
  { code: "UG", name: "Uganda", flag: getFlagUrl("UG") },
  {
    code: "UM",
    name: "United States Minor Outlying Islands",
    flag: getFlagUrl("UM"),
  },
  { code: "US", name: "United States", flag: getFlagUrl("US") },
  { code: "US", name: "USA", flag: getFlagUrl("US") },
  { code: "UY", name: "Uruguay", flag: getFlagUrl("UY") },
  { code: "UZ", name: "Uzbekistan", flag: getFlagUrl("UZ") },
  { code: "VA", name: "Vatican City", flag: getFlagUrl("VA") },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    flag: getFlagUrl("VC"),
  },
  { code: "VE", name: "Venezuela", flag: getFlagUrl("VE") },
  { code: "VG", name: "British Virgin Islands", flag: getFlagUrl("VG") },
  { code: "VI", name: "U.S. Virgin Islands", flag: getFlagUrl("VI") },
  { code: "VN", name: "Vietnam", flag: getFlagUrl("VN") },
  { code: "VU", name: "Vanuatu", flag: getFlagUrl("VU") },
  { code: "WF", name: "Wallis and Futuna", flag: getFlagUrl("WF") },
  { code: "WS", name: "Samoa", flag: getFlagUrl("WS") },
  { code: "YE", name: "Yemen", flag: getFlagUrl("YE") },
  { code: "YT", name: "Mayotte", flag: getFlagUrl("YT") },
  { code: "ZA", name: "South Africa", flag: getFlagUrl("ZA") },
  { code: "ZM", name: "Zambia", flag: getFlagUrl("ZM") },
  { code: "ZW", name: "Zimbabwe", flag: getFlagUrl("ZW") },
];
